GET http://localhost:5000/products

###
GET http://localhost:5000/products/1

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Daily Lyra",
    "desc" : "well",
    "price" : "100000"
}

###
PATCH  http://localhost:5000/products/1
Content-Type: application/json

{
    "name": "Daily Lyra Updated",
    "desc" : "well meledakkk",
    "price" : "200000"
}

###
DELETE  http://localhost:5000/products/2
